[package]
name = "a2"
version = "0.6.2"
authors = [
  "Julius de Bruijn <julius@nauk.io>",
  "Sergey Tkachenko <seriy.tkachenko@gmail.com>",
]
license = "MIT"
readme  = "README.md"
description = "A native, asynchronous Apple push notification client"
keywords    = ["apns", "apple", "push", "async", "http2"]
repository  = "https://github.com/pimeys/a2.git"
homepage    = "https://github.com/pimeys/a2"
documentation = "https://docs.rs/a2"
edition = "2018"

[features]
default = ["openssl"]
ring = ["dep:ring", "pem"]

[dependencies]
serde = "1"
erased-serde = "0.3"
serde_derive = "1"
serde_json = "1"
thiserror = "1"
openssl = { version = "0.10", optional = true }
futures = "0.3"
http = "0.2"
base64 = "0.13"
log = "0.4"
hyper = { version = "0.14", default-features = false, features = ["client", "http2"] }
hyper-alpn = "0.3"
pem = { version = "1.0.2", optional = true }
ring = { version = "0.16.20", features = ["std"], optional = true }
cfg-if = "1.0.0"

[dev-dependencies]
argparse = "0.2"
pretty_env_logger = "0.4"
indoc = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
